### ISSUE TITLE
[Epic] Composable Commands

### ISSUE THREAD

**Issue by DrBarnabus** [DrBarnabus/pullrequest-automation#6]
# 👑 Composable Commands

## Description

While the commands available at present are configurable they might not apply to all situations users of the action may want.

To make the action more configurable we can implement the concept of "Composable Commands" which will allow allocation of a trigger command and a set of actions/steps that will be triggered once the command has been matched. The configuration will then follow a pattern such as:

```yaml
commands:
- trigger: Merge and Promote to main!
  actions:
  - action: check-for-merge-conflicts
    name: Check for Merge Conflicts
    with:
      baseRef: development
      comparisonBaseRef: main
  - action: merge-branch
    name: Merge to development
    with:
      baseRef: development
  - action: create-pull-request
    name: Create Pull Request into main
    with:
      baseRef: main
      headRef: development
      label: generated
```

As well as providing more customizability it also simplifies the development loop for adding new commands/actions without breaking changes as individual actions could be updated and provided with a vN (e.g. check-for-merge-conflicts-v2)

## Tasks

- [x] #7 
- [x] #8 
- [x] #9 
- [x] #10 
- [x] #11 
- [x] #12
