### ISSUE TITLE
Composable Commands - Create "base" configuration structure

### ISSUE THREAD

**Issue by DrBarnabus** [DrBarnabus/pullrequest-automation#8]
Create base configuration structure for Composable Commands feature.

``` yaml
commands:
- trigger: <string>
  actions:
  - action: <string-enum>
    name: <string>
    with:
      <object with action configuration>
  - action: ...
- trigger: ...
```
